''' =========================================================================================== '''
# Our Chat RESTful App

''' =========================================================================================== '''
# third-party imports
from flask import render_template
from flask import request
from flask import redirect
from flask import session
from flask import jsonify

# local imports
from app import create_app
from app import models
from app import db
from env import FLASK_CONFIG

''' =========================================================================================== '''
# instantiate the app
app = create_app(FLASK_CONFIG)

''' =========================================================================================== '''
# define our routes

'''
Description: Render the main chat view here from templates
Input: None
Return Type: HTML, a view generated by render_template()
'''
@app.route('/')
def chat_view():
    title = 'Home'
    flutters = models.Message.query.all()
    users = models.User.query.all()
    usersInOrder = []
    for flutter in flutters:
        usersInOrder.append(models.User.query.filter(models.User.id == flutter.user_id).first())
    return render_template('home/index.html', title=title, flutters=flutters, associated_users=usersInOrder, users=users)

'''
Description: Render the user profile here from templates
Input: user_id
Return Type: HTML, a view generated by render_template()
'''
@app.route('/user/<int:user_id>')
def user_profile(user_id):
    user = models.User.query.filter(models.User.id == user_id).first()
    flutters = models.Message.query.filter(models.Message.user_id == user.id)
    return render_template('home/userprofile.html', user=user, flutters=flutters, title=user.username)

'''
Description: Retrieve a collection of users from the database
Input: None
Return Type: JSON, a JSON object containing the list of users
See here for details: http://flask.pocoo.org/docs/0.12/api/#flask.json.jsonify
'''
@app.route('/users')
def user():
    users = models.User.query.all()
    jsonToReturn = []
    for user in users:
        jsonToReturn.append({'username': user.username, 'first_name': user.first_name, 'last_name': user.last_name})
    return jsonify(jsonToReturn)

'''
Description: Retrieve a collection of messages from the database
Input: None
Return Type: JSON, a JSON object containing the list of messages
See here for details: http://flask.pocoo.org/docs/0.12/api/#flask.json.jsonify
'''
@app.route('/messages')
def flutter():
    flutters=  models.Message.query.all()
    jsonToReturn = []
    for flutter in flutters:
        jsonToReturn.append({'message': flutter.message, 'author': models.User.query.filter(models.User.id == flutter.user_id).first().username})
    return jsonify(jsonToReturn)

@app.route('/hello/<username>')
def small_route(username):
    return render_template('home/hello.html', the_name=username)

''' =========================================================================================== '''
# run the app
if __name__ == '__main__':
    app.run()
