''' =========================================================================================== '''
# Our Chat RESTful App

''' =========================================================================================== '''
# third-party imports
from flask import render_template
from flask import request
from flask import redirect
from flask import session
from flask import jsonify

# local imports
from app import create_app
from app import models
from app import db
from env import FLASK_CONFIG

''' =========================================================================================== '''
# instantiate the app
app = create_app(FLASK_CONFIG)

''' =========================================================================================== '''
# define our routes

''' If user tries to access undefined page, post 404 error'''
@app.errorhandler(404)
def page_not_found(e):
	return render_template('home/404.html'), 404

'''
Description: Render the main chat view here from templates
Input: None
Return Type: HTML, a view generated by render_template()
'''
@app.route('/')
def chat_view():
    return render_template('home/index.html')

@app.route('/submit', methods=['POST'])
def subscribing():
    the_subscriber_fname = request.form['name']
    the_subscriber_email = request.form['email_address']

    new_db_subscriber = models.Subscriber(first_name=the_subscriber_fname, email=the_subscriber_email)
    print("new subscriber: ", new_db_subscriber.first_name, new_db_subscriber.email)

    db.session.add(new_db_subscriber)
    db.session.commit()

    return render_template('home/thankyou.html', first_name=the_subscriber_fname)
''' =========================================================================================== '''
# run the app
if __name__ == '__main__':
    app.run()
